# This workflow runs automated tests for the backend service, including:
# - Linting to ensure code quality
# - Unit tests across multiple Node.js versions
# - Security audit checks
# - Test coverage reporting
name: Backend Service Quality Checks

on:
  push:
    paths:
      - 'src/backend/**'
  pull_request:
    paths:
      - 'src/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: src/backend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd src/backend
        npm ci
    
    - name: Run linting
      run: |
        cd src/backend
        npm run lint
    
    - name: Run tests
      run: |
        cd src/backend
        npm test
    
    - name: Run security audit
      run: |
        cd src/backend
        npm audit
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: src/backend/coverage 