# TODO: Before enabling this workflow, add the following secrets to the repository:
# 1. AUDIT_API_KEY: Your Snyk API key for testing
# 2. AUDIT_ORG_ID: Your Snyk Organization ID for testing
#
# To add secrets:
# 1. Go to repository Settings
# 2. Navigate to Secrets and variables > Actions
# 3. Click "New repository secret"
# 4. Add each secret with their respective values

name: Test CLI

on:
  push:
    paths:
      - 'src/backend/**'
  pull_request:
    paths:
      - 'src/backend/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: src/backend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd src/backend
        npm ci
    
    - name: Test CLI with org ID
      id: cli-test
      run: |
        cd src/backend
        node src/index.js --api-key "${{ secrets.AUDIT_API_KEY }}" --org-id "${{ secrets.AUDIT_ORG_ID }}" --from-date 2025-05-25T00:00:00Z --to-date 2025-05-29T23:59:59Z
        if [ $? -eq 0 ]; then
          echo "CLI test with org ID passed"
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "CLI test with org ID failed"
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Check if HTML report was generated
      working-directory: src/backend
      id: check-report
      run: |
        echo "Checking for HTML report..."
        REPORT_FILE=$(ls audit_logs_report_*.html 2>/dev/null)
        if [ -z "$REPORT_FILE" ]; then
          echo "HTML report was not generated"
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi
        echo "HTML report was generated: $REPORT_FILE"
        echo "status=success" >> $GITHUB_OUTPUT
        echo "report_file=$REPORT_FILE" >> $GITHUB_OUTPUT

    - name: Upload HTML report as artifact
      uses: actions/upload-artifact@v4
      if: steps.check-report.outputs.status == 'success'
      with:
        name: audit-report
        path: src/backend/audit_logs_report_*.html
        if-no-files-found: error

    - name: Report Status
      if: always()
      run: |
        echo "CLI Test Status: ${{ steps.cli-test.outputs.status }}"
        echo "Report Generation Status: ${{ steps.check-report.outputs.status }}"
        if [ "${{ steps.check-report.outputs.status }}" == "success" ]; then
          echo "Generated Report: ${{ steps.check-report.outputs.report_file }}"
        fi 
